#!/usr/bin/env python3
# methods/postprocess/figures_validation.py (validation figures; former 05_validate.py)
"""
Stage 2 — Validate & compare parametric reservoir policies in Pywr-DRB

Overview
--------
This script automates a full validation workflow that:
  1) Loads multi-objective optimization (BORG) results, selects "focal" solutions
     per reservoir/policy (release/storage/average NSE objective optima, Best Average All,
     plus advanced picks) using OBJ_LABELS and OBJ_FILTER_BOUNDS.
  2) Runs an independent reservoir simulation (methods.reservoir.model.Reservoir)
     with the chosen policy parameters over a validation window using observed
     inflows (MGD) and compares simulated release = (release + spill) and storage.
  3) Builds and runs a Pywr-DRB model with an inline ParametricReservoirRelease
     node that uses the same policy parameters (“parametric run”).
  4) Builds and runs a default Pywr-DRB model with no overrides (“default run”).
  5) Generates comparison figures and (optionally) CSV time series for analysis.

Generated Figures
-----------------
Saved under ``resolve_figure_root(FIG_DIR)`` (override with ``--outdir``), in flat ``figN_*`` folders:

- ``fig7_validation_dynamics/`` — 2×1 dynamics + release FDC + optional NSE/params (Figure 7).

- ``fig8_error_vs_flow_percentile/release_combined_*.png`` — single composite: release error
  time series (calendar month shading), error vs flow percentile, and 2×2 seasonal panels
  (independent, parametric, default) (Figure 8). Y-axis is **relative error**,
  ``100 (sim − obs) / max(obs, ε)`` (% of observed release), unless disabled via
  ``use_relative_error_pct=False`` in code. Generated by default; use
  ``--skip-error-ts-release-multi`` to omit (faster).

- ``fig12_lower_basin_context/`` — five-panel lower-basin MRF context.

- ``fig13_trenton_flow/`` — Trenton timeseries + FDC (optional min-flow target line).

Saved Series (optional)
-----------------------
When --save-series is set, CSVs for independent, parametric, and default runs
are written for both storage and release (sliced to the validation window).

Comparisons (optional)
----------------------
With --compare-series the script compares independent vs Pywr-DRB (parametric)
series using numpy.allclose with user-specified tolerances:
  • rtol: relative tolerance
  • atol: absolute tolerance
See NumPy documentation for details; (rtol=0, atol=0) enforces exact equality.

Inputs & Dependencies
---------------------
- Reads BORG output CSVs from OUTPUT_DIR using methods.load.results.load_results.
- Observations via methods.load.observations.get_observational_training_data.
- Reservoir capacity and policy metadata from methods.config.
- Pywr-DRB model construction/run via pywrdrb.ModelBuilder/Model/Data.
- If Prompton downstream gage observations are missing, the script can attempt
  an NWIS daily-values fetch (cfs→MGD) to fill releases for plotting.

Key Assumptions
---------------
- Units: inflow/release/spill in MGD; storage in MG.
- Validation window applies to figures and CSV outputs; Pywr-DRB runs use
  --pywr-start/--pywr-end when both are set, otherwise ``model_date_ranges[inflow_type]``
  from pywrdrb, then outputs are sliced to the validation/plot window.
- Policy parameter vectors are taken from the selected BORG row; bounds are
  checked against policy_param_bounds (out-of-bounds values are only warned).

CLI
---
Examples:

# All default reservoirs/policies, all focal picks, full figure set:
python -m methods.postprocess.figures_validation --save-series --compare-series --rtol 1e-8 --atol 1e-4

# Subset: STARFIT for FE Walter & Prompton, two focal picks (legacy ``--picks`` strings are normalized to
# canonical labels; see ``methods.plotting.pick_labels``):
python -m methods.postprocess.figures_validation \
  --reservoirs fewalter prompton \
  --policies STARFIT \
  --picks "Best Release NSE" "Best Average All" \
  --save-series --compare-series

# Default Pywr-DRB period & inflow dataset (uses model_date_ranges for the inflow key):
python -m methods.postprocess.figures_validation --pywr-inflow-type pub_nhmv10_BC_withObsScaled

# Override Pywr timestepper explicitly:
python -m methods.postprocess.figures_validation \
  --pywr-start 1983-10-01 --pywr-end 2023-12-31 \
  --pywr-inflow-type pub_nhmv10_BC_withObsScaled

# Perfect-information column family in Pywr (optional):
CEE_PYWR_FLOW_PREDICTION_MODE=perfect_foresight python -m methods.postprocess.figures_validation --pywr-flow-prediction-mode auto

Arguments
---------
--reservoirs            List of reservoir names (default: methods.config.reservoir_options)
--policies              List of policy types (STARFIT|RBF|PWL; default: methods.config.policy_type_options)
--picks                 Focal picks to plot (default: ``DEFAULT_STAGE1_PICKS``). If omitted on the CLI,
                        ``CEE_DESIRED_PICKS`` (comma-separated, same as stage 1) overrides the default list.
--val-start/--val-end   Validation window for figures/CSVs (default: 1980-01-01 to 2018-12-31)
--pywr-start/--pywr-end Pywr-DRB model run window (omit both to use model_date_ranges[inflow_type])
--pywr-inflow-type      Pywr-DRB inflow dataset key (default provided)
--outdir                Figure root only (PNG/CSV); Pywr HDF5/JSON use CEE_PYWR_WORK_DIR (default: pywr_data/pywr_tmp_runs)
--save-series           Write CSVs for all plotted series
--compare-series        Compare independent vs parametric series (rtol/atol)
--rtol/--atol           Tolerances for numpy.allclose in comparisons
"""
import os
import re
import sys
import argparse
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# ==== project imports ====
from methods.config import (
    OBJ_LABELS, OBJ_FILTER_BOUNDS, SENSES_ALL,
    reservoir_options, policy_type_options,
    OUTPUT_DIR, FIG_DIR, PROCESSED_DATA_DIR,
    reservoir_capacity,
    get_pywr_work_dir,
)
from methods.borg_paths import resolve_borg_moea_csv_path, resolve_figure_root
from methods.load.results import load_results
from methods.load.observations import get_observational_training_data
from methods.reservoir.model import Reservoir

from methods.postprocess.pywr_parametric_run import (
    parametric_hdf5_stem,
    parametric_result_from_h5_path,
    run_pywr_parametric_multi,
    run_pywr_parametric_single_res,
)

from methods.plotting.plot_dynamics_2x1 import plot_2x1_dynamics
from methods.plotting.starfit_nor import nor_pct_series_on_index, try_compute_starfit_nor_pct_by_doy
from methods.plotting.plot_lower_basin_5panel import plot_lower_basin_fivepanel
from methods.utils.policy_parameter_naming import get_param_names_for_policy
from methods.plotting.plot_error_diagnostics import plot_fig6_combined_release_diagnostics
from methods.plotting.plot_pareto_ensemble_uncertainty import PARAMETRIC_MOEA_RESERVOIR_KEYS
from methods.plotting.theme import (
    SERIES_COLORS,
    SERIES_LINESTYLES,
    SERIES_LINEWIDTHS,
    get_parametric_color,
)
from methods.postprocess.pywr_output_metadata import (
    normalize_borg_row_label,
    print_policy_row_counts,
)


def _default_pywr_flow_mode() -> str:
    """ModelBuilder ``flow_prediction_mode``; set CEE_PYWR_FLOW_PREDICTION_MODE or default regression_disagg."""
    v = os.environ.get("CEE_PYWR_FLOW_PREDICTION_MODE", "").strip()
    return v if v else "regression_disagg"


# advanced selection utilities (same as 04)
from methods.plotting.selection_utils import (
    compute_and_apply_advanced_highlights,  # adds 'highlight_adv' + returns cand_map
    ADVANCED_COLORS,
)
from methods.plotting.pick_labels import (
    AVERAGE_NSE_OBJECTIVE_OPTIMUM,
    BEST_AVERAGE_ALL,
    DEFAULT_STAGE1_PICKS,
    RELEASE_NSE_OBJECTIVE_OPTIMUM,
    STORAGE_NSE_OBJECTIVE_OPTIMUM,
    iter_pick_lookup_labels,
    normalize_pick_label,
    pick_filename_slug,
    resolve_cand_map_value,
)

import pywrdrb
from pywrdrb.utils.dates import model_date_ranges

# pywr currently triggers a pandas FutureWarning when resampling PeriodIndex-backed
# dataframes internally. Filter it once for this script to keep stderr actionable.
warnings.filterwarnings(
    "ignore",
    message="Resampling with a PeriodIndex is deprecated.*",
    category=FutureWarning,
)


def _parse_figure_numbers() -> set[int] | None:
    raw = os.environ.get("CEE_FIGURE_NUMBERS", "").strip()
    if not raw:
        return None
    out: set[int] = set()
    for token in raw.replace(",", " ").split():
        if "-" in token:
            a, b = token.split("-", 1)
            lo, hi = sorted((int(a), int(b)))
            out.update(range(lo, hi + 1))
        else:
            out.add(int(token))
    return out


def _want_figure(n: int, enabled: set[int] | None) -> bool:
    return True if enabled is None else (int(n) in enabled)


def _figure_picks_from_env() -> list[str]:
    raw = os.environ.get("CEE_DESIRED_PICKS", "").strip()
    if not raw:
        return list(DEFAULT_STAGE1_PICKS)
    picks = [normalize_pick_label(p.strip()) for p in raw.split(",") if p.strip()]
    return picks if picks else list(DEFAULT_STAGE1_PICKS)


def _figure_policies_from_env() -> list[str]:
    base = [str(p).upper() for p in policy_type_options]
    raw = os.environ.get("CEE_FIGURE_POLICIES", "").strip()
    if not raw:
        return base
    out = []
    allowed = set(base)
    for tok in raw.split(","):
        t = tok.strip().upper()
        if t in allowed and t not in out:
            out.append(t)
    return out if out else base


# ---------- helpers ----------
def _resolve_pywr_simulation_dates(
    inflow_type: str,
    pywr_start: str | None,
    pywr_end: str | None,
) -> tuple[str, str]:
    """
    If both ``pywr_start`` and ``pywr_end`` are omitted, use ``model_date_ranges``
    for ``inflow_type`` (full span packaged for that dataset). If both are given,
    use them. If only one is given, exit with an error.
    """
    if pywr_start is None and pywr_end is None:
        if inflow_type not in model_date_ranges:
            raise KeyError(
                f"Unknown --pywr-inflow-type={inflow_type!r}; "
                f"known keys include: {sorted(model_date_ranges)}"
            )
        s, e = model_date_ranges[inflow_type]
        return str(s), str(e)
    if pywr_start is None or pywr_end is None:
        raise SystemExit(
            "Provide both --pywr-start and --pywr-end, or omit both to use "
            "pywrdrb.utils.dates.model_date_ranges for --pywr-inflow-type."
        )
    return pywr_start, pywr_end


# ---------- helpers ----------
def ensure_dir(p: str) -> str:
    Path(p).mkdir(parents=True, exist_ok=True)
    return p

def safe_name(s) -> str:
    return re.sub(r'[^A-Za-z0-9._-]+', '_', str(s)).strip('_') or "pick"


def figure_date_tag(start: str, end: str) -> str:
    """Compact date range token for filenames."""
    s = safe_name(str(start)[:10])
    e = safe_name(str(end)[:10])
    return f"{s}_to_{e}"


def _idxmin_safe(series: pd.Series):
    """
    Return idxmin for numeric values while tolerating all-NA rows/series.
    Falls back to the first index entry if everything is NA/non-finite.
    """
    if series is None or len(series) == 0:
        return None
    ser = pd.to_numeric(series, errors="coerce")
    ser = ser.replace([np.inf, -np.inf], np.nan)
    if ser.notna().any():
        return ser.idxmin()
    return series.index[0]

def compare_series(a: pd.Series, b: pd.Series, name: str, rtol=0.0, atol=0.0):
    a = a.astype(float); b = b.astype(float)
    idx = a.index.intersection(b.index)
    a = a.loc[idx]; b = b.loc[idx]
    if len(a) == 0:
        print(f"[WARN] {name}: no overlapping index to compare.")
        return False
    if rtol == 0.0 and atol == 0.0:
        same_mask = (a.values == b.values)
        ok = bool(same_mask.all())
        print(f"[COMPARE:{name}] exact equality: {ok} over {len(a)} steps.")
        if not ok:
            first_bad = int(np.where(~same_mask)[0][0])
            ts = a.index[first_bad]
            print(
                f"[COMPARE:{name}] first divergence @ {ts}: "
                f"a={float(a.iloc[first_bad]):.10g}, b={float(b.iloc[first_bad]):.10g}"
            )
        return ok
    allclose_mask = np.isclose(a.values, b.values, rtol=rtol, atol=atol, equal_nan=True)
    ok = bool(allclose_mask.all())
    print(f"[COMPARE:{name}] allclose rtol={rtol} atol={atol}: {ok} over {len(a)} steps.")
    if not ok:
        first_bad = int(np.where(~allclose_mask)[0][0])
        ts = a.index[first_bad]
        abs_err = float(np.abs(a.iloc[first_bad] - b.iloc[first_bad]))
        print(
            f"[COMPARE:{name}] first divergence @ {ts}: "
            f"a={float(a.iloc[first_bad]):.10g}, b={float(b.iloc[first_bad]):.10g}, "
            f"abs_err={abs_err:.10g}"
        )
    return ok


def _effective_plot_window(
    series_list: list[pd.Series | None],
    fallback_start: str,
    fallback_end: str,
) -> tuple[str, str]:
    """
    Return actual overlapping date window across available series.
    Falls back to requested window when no finite overlap exists.
    """
    idx: pd.Index | None = None
    for s in series_list:
        if s is None:
            continue
        ss = pd.to_numeric(s, errors="coerce").dropna()
        if len(ss) == 0:
            continue
        idx = ss.index if idx is None else idx.intersection(ss.index)
        if idx is not None and len(idx) == 0:
            break
    if idx is None or len(idx) == 0:
        return fallback_start, fallback_end
    idx = idx.sort_values()
    return str(idx.min().date()), str(idx.max().date())


def _fdc_xy(series: pd.Series):
    vals = pd.to_numeric(series, errors="coerce").dropna().astype(float).values
    if len(vals) == 0:
        return None, None
    vals = vals[vals >= 0.0]
    if len(vals) == 0:
        return None, None
    vals_desc = np.sort(vals)[::-1]
    n = len(vals_desc)
    exceed = 100.0 * (np.arange(1, n + 1) / (n + 1))
    return exceed, vals_desc


def _align_three(obs: pd.Series | None, default: pd.Series | None, new: pd.Series | None):
    idx = None
    for s in (obs, default, new):
        if s is None:
            continue
        ss = pd.to_numeric(s, errors="coerce").dropna()
        if len(ss) == 0:
            continue
        idx = ss.index if idx is None else idx.intersection(ss.index)
    if idx is None or len(idx) == 0:
        return None, None, None
    idx = idx.sort_values()
    return (
        pd.to_numeric(obs.reindex(idx), errors="coerce") if obs is not None else None,
        pd.to_numeric(default.reindex(idx), errors="coerce") if default is not None else None,
        pd.to_numeric(new.reindex(idx), errors="coerce") if new is not None else None,
    )


def plot_release_distribution_diagnostics(
    *,
    obs_release: pd.Series,
    default_release: pd.Series,
    new_release: pd.Series,
    title_prefix: str,
    save_path: str,
):
    obs, dft, new = _align_three(obs_release, default_release, new_release)
    if obs is None:
        return
    fig, axes = plt.subplots(2, 2, figsize=(12.5, 8.0))
    ax_cdf_lin, ax_cdf_log = axes[0]
    ax_hist_lin, ax_hist_log = axes[1]

    def _plot_cdf(ax, s, label, color, ls):
        x = np.sort(pd.to_numeric(s, errors="coerce").dropna().values.astype(float))
        if len(x) == 0:
            return
        y = np.linspace(0.0, 1.0, len(x))
        ax.plot(x, y, label=label, color=color, ls=ls, lw=2.0)

    _plot_cdf(ax_cdf_lin, obs, "Observed", SERIES_COLORS["observed"], SERIES_LINESTYLES["observed"])
    _plot_cdf(ax_cdf_lin, dft, "Default (modified STARFIT)", SERIES_COLORS["default"], SERIES_LINESTYLES["default"])
    _plot_cdf(ax_cdf_lin, new, "New (optimized)", SERIES_COLORS["parametric"], SERIES_LINESTYLES["parametric"])
    ax_cdf_lin.set_title("Release CDF (linear x)")
    ax_cdf_lin.set_xlabel("Release (MGD)")
    ax_cdf_lin.set_ylabel("Cumulative probability")
    ax_cdf_lin.grid(alpha=0.3)
    ax_cdf_lin.legend(loc="lower right", fontsize=8)

    # Log-x variants (release must be > 0)
    obs_pos = obs[obs > 0].dropna()
    dft_pos = dft[dft > 0].dropna()
    new_pos = new[new > 0].dropna()
    _plot_cdf(ax_cdf_log, obs_pos, "Observed", SERIES_COLORS["observed"], SERIES_LINESTYLES["observed"])
    _plot_cdf(ax_cdf_log, dft_pos, "Default (modified STARFIT)", SERIES_COLORS["default"], SERIES_LINESTYLES["default"])
    _plot_cdf(ax_cdf_log, new_pos, "New (optimized)", SERIES_COLORS["parametric"], SERIES_LINESTYLES["parametric"])
    ax_cdf_log.set_xscale("log")
    ax_cdf_log.set_title("Release CDF (log x)")
    ax_cdf_log.set_xlabel("Release (MGD, log scale)")
    ax_cdf_log.set_ylabel("Cumulative probability")
    ax_cdf_log.grid(alpha=0.3, which="both")
    ax_cdf_log.legend(loc="lower right", fontsize=8)

    bins_lin = 40
    ax_hist_lin.hist(obs.dropna().values, bins=bins_lin, density=True, alpha=0.35, color=SERIES_COLORS["observed"], label="Observed")
    ax_hist_lin.hist(dft.dropna().values, bins=bins_lin, density=True, alpha=0.35, color=SERIES_COLORS["default"], label="Default (modified STARFIT)")
    ax_hist_lin.hist(new.dropna().values, bins=bins_lin, density=True, alpha=0.35, color=SERIES_COLORS["parametric"], label="New (optimized)")
    ax_hist_lin.set_title("Release histogram / density (linear x)")
    ax_hist_lin.set_xlabel("Release (MGD)")
    ax_hist_lin.set_ylabel("Density")
    ax_hist_lin.grid(alpha=0.3)
    ax_hist_lin.legend(loc="upper right", fontsize=8)

    if len(obs_pos) and len(dft_pos) and len(new_pos):
        vals = np.concatenate([obs_pos.values, dft_pos.values, new_pos.values])
        vmin, vmax = float(np.nanmin(vals)), float(np.nanmax(vals))
        if np.isfinite(vmin) and np.isfinite(vmax) and vmax > vmin:
            bins_log = np.logspace(np.log10(vmin), np.log10(vmax), 40)
        else:
            bins_log = 40
    else:
        bins_log = 40
    ax_hist_log.hist(obs_pos.values, bins=bins_log, density=True, alpha=0.35, color=SERIES_COLORS["observed"], label="Observed")
    ax_hist_log.hist(dft_pos.values, bins=bins_log, density=True, alpha=0.35, color=SERIES_COLORS["default"], label="Default (modified STARFIT)")
    ax_hist_log.hist(new_pos.values, bins=bins_log, density=True, alpha=0.35, color=SERIES_COLORS["parametric"], label="New (optimized)")
    ax_hist_log.set_xscale("log")
    ax_hist_log.set_title("Release histogram / density (log x)")
    ax_hist_log.set_xlabel("Release (MGD, log scale)")
    ax_hist_log.set_ylabel("Density")
    ax_hist_log.grid(alpha=0.3, which="both")
    ax_hist_log.legend(loc="upper right", fontsize=8)

    fig.suptitle(title_prefix)
    fig.tight_layout()
    fig.savefig(save_path, dpi=180, bbox_inches="tight")
    plt.close(fig)


def plot_operational_space(
    *,
    obs_storage_mg: pd.Series,
    obs_release: pd.Series,
    default_storage_mg: pd.Series,
    default_release: pd.Series,
    new_storage_mg: pd.Series,
    new_release: pd.Series,
    capacity_mg: float,
    title_prefix: str,
    save_path: str,
):
    obs_s, dft_s, new_s = _align_three(obs_storage_mg, default_storage_mg, new_storage_mg)
    obs_r, dft_r, new_r = _align_three(obs_release, default_release, new_release)
    if obs_s is None or obs_r is None:
        return
    idx = obs_s.index.intersection(obs_r.index)
    if len(idx) == 0:
        return
    obs_s = obs_s.loc[idx]; dft_s = dft_s.loc[idx]; new_s = new_s.loc[idx]
    obs_r = obs_r.loc[idx]; dft_r = dft_r.loc[idx]; new_r = new_r.loc[idx]

    to_pct = lambda s: 100.0 * pd.to_numeric(s, errors="coerce") / float(capacity_mg)
    fig, ax = plt.subplots(figsize=(7, 5.5))
    ax.scatter(to_pct(obs_s), obs_r, s=8, alpha=0.18, color=SERIES_COLORS["observed"], label="Observed")
    ax.scatter(to_pct(dft_s), dft_r, s=8, alpha=0.18, color=SERIES_COLORS["default"], label="Default (modified STARFIT)")
    ax.scatter(to_pct(new_s), new_r, s=8, alpha=0.18, color=SERIES_COLORS["parametric"], label="New (optimized)")
    ax.set_xlabel("Storage (% capacity)")
    ax.set_ylabel("Release (MGD)")
    ax.set_title(title_prefix + " — Operational space")
    ax.grid(alpha=0.3)
    ax.legend(loc="upper left", fontsize=8)
    fig.tight_layout()
    fig.savefig(save_path, dpi=180, bbox_inches="tight")
    plt.close(fig)


def plot_seasonal_multipanel(
    *,
    obs_storage_mg: pd.Series,
    obs_release: pd.Series,
    default_storage_mg: pd.Series,
    default_release: pd.Series,
    new_storage_mg: pd.Series,
    new_release: pd.Series,
    capacity_mg: float,
    title_prefix: str,
    save_path: str,
):
    # Align series first so seasonal summaries are apples-to-apples across
    # observed/default/new and consistent with the same datetime support.
    obs_s, dft_s, new_s = _align_three(obs_storage_mg, default_storage_mg, new_storage_mg)
    obs_r, dft_r, new_r = _align_three(obs_release, default_release, new_release)
    if obs_s is None or obs_r is None:
        return

    idx = obs_s.index.intersection(obs_r.index)
    if len(idx) == 0:
        return
    obs_s = obs_s.loc[idx]
    dft_s = dft_s.loc[idx]
    new_s = new_s.loc[idx]
    obs_r = obs_r.loc[idx]
    dft_r = dft_r.loc[idx]
    new_r = new_r.loc[idx]

    def _to_df(s, name):
        ss = pd.to_numeric(s, errors="coerce").dropna().astype(float)
        df = pd.DataFrame({"v": ss.values}, index=ss.index)
        df["doy"] = df.index.dayofyear
        return df.rename(columns={"v": name})

    oS = _to_df(obs_s, "obsS"); oR = _to_df(obs_r, "obsR")
    dS = _to_df(dft_s, "dS"); dR = _to_df(dft_r, "dR")
    nS = _to_df(new_s, "nS"); nR = _to_df(new_r, "nR")
    if oS.empty or oR.empty:
        return
    cap = float(capacity_mg)
    oS["obsS"] = 100.0 * oS["obsS"] / cap
    dS["dS"] = 100.0 * dS["dS"] / cap
    nS["nS"] = 100.0 * nS["nS"] / cap

    fig, axes = plt.subplots(1, 2, figsize=(12.5, 4.8))
    axS, axR = axes

    for ax, obsdf, ddef, ndf, obs_col, d_col, n_col, ylabel, ttl in [
        (axS, oS, dS, nS, "obsS", "dS", "nS", "Storage (% capacity)", "Storage vs day-of-year (median)"),
        (axR, oR, dR, nR, "obsR", "dR", "nR", "Release (MGD)", "Release vs day-of-year (median)"),
    ]:
        env = obsdf.groupby("doy")[obs_col].agg(["min", "max"]).reindex(range(1, 367))
        ax.fill_between(
            env.index.values,
            env["min"].values,
            env["max"].values,
            color=SERIES_COLORS["observed"],
            alpha=0.15,
            label="Observed envelope (daily min-max by DOY)",
        )
        med_obs = obsdf.groupby("doy")[obs_col].median().reindex(range(1, 367))
        med_d = ddef.groupby("doy")[d_col].median().reindex(range(1, 367))
        med_n = ndf.groupby("doy")[n_col].median().reindex(range(1, 367))
        ax.plot(med_obs.index.values, med_obs.values, color=SERIES_COLORS["observed"], ls=SERIES_LINESTYLES["observed"], lw=2.0, label="Observed (DOY median)")
        ax.plot(med_d.index.values, med_d.values, color=SERIES_COLORS["default"], ls=SERIES_LINESTYLES["default"], lw=2.0, label="Default (modified STARFIT, DOY median)")
        ax.plot(med_n.index.values, med_n.values, color=SERIES_COLORS["parametric"], ls=SERIES_LINESTYLES["parametric"], lw=2.0, label="New (optimized, DOY median)")
        ax.set_title(ttl)
        ax.set_xlabel("Day of year")
        ax.set_ylabel(ylabel)
        ax.grid(alpha=0.3)
        ax.set_xlim(1, 366)

    handles, labels = axS.get_legend_handles_labels()
    fig.legend(handles, labels, loc="lower center", ncol=2, fontsize=8)
    fig.suptitle(title_prefix + " — Seasonal multi-panel (aggregated by day-of-year)")
    idx_start = pd.Timestamp(idx.min()).date()
    idx_end = pd.Timestamp(idx.max()).date()
    fig.text(
        0.5,
        0.91,
        f"Lines show DOY medians; shaded band is observed DOY min-max ({idx_start} to {idx_end}, n={len(idx)} days).",
        ha="center",
        va="center",
        fontsize=8,
    )
    fig.tight_layout(rect=(0, 0.10, 1, 0.93))
    fig.savefig(save_path, dpi=180, bbox_inches="tight")
    plt.close(fig)


def plot_seasonal_multipanel_v2_ranges(
    *,
    obs_storage_mg: pd.Series,
    obs_release: pd.Series,
    default_storage_mg: pd.Series,
    default_release: pd.Series,
    new_storage_mg: pd.Series,
    new_release: pd.Series,
    capacity_mg: float,
    title_prefix: str,
    save_path: str,
):
    obs_s, dft_s, new_s = _align_three(obs_storage_mg, default_storage_mg, new_storage_mg)
    obs_r, dft_r, new_r = _align_three(obs_release, default_release, new_release)
    if obs_s is None or obs_r is None:
        return
    idx = obs_s.index.intersection(obs_r.index)
    if len(idx) == 0:
        return
    obs_s, dft_s, new_s = obs_s.loc[idx], dft_s.loc[idx], new_s.loc[idx]
    obs_r, dft_r, new_r = obs_r.loc[idx], dft_r.loc[idx], new_r.loc[idx]

    def _to_df(s, name):
        ss = pd.to_numeric(s, errors="coerce").dropna().astype(float)
        df = pd.DataFrame({"v": ss.values}, index=ss.index)
        df["doy"] = df.index.dayofyear
        return df.rename(columns={"v": name})

    oS = _to_df(100.0 * obs_s / float(capacity_mg), "obsS")
    dS = _to_df(100.0 * dft_s / float(capacity_mg), "dS")
    nS = _to_df(100.0 * new_s / float(capacity_mg), "nS")
    oR = _to_df(obs_r, "obsR")
    dR = _to_df(dft_r, "dR")
    nR = _to_df(new_r, "nR")

    fig, axes = plt.subplots(1, 2, figsize=(12.5, 4.8))
    axS, axR = axes
    specs = [
        (axS, oS, dS, nS, "obsS", "dS", "nS", "Storage (% capacity)", "Storage vs day-of-year (range + median)"),
        (axR, oR, dR, nR, "obsR", "dR", "nR", "Release (MGD)", "Release vs day-of-year (range + median)"),
    ]
    for ax, obsdf, ddef, ndf, oc, dc, nc, ylab, ttl in specs:
        for df, col, color, ls, lbl, a in [
            (obsdf, oc, SERIES_COLORS["observed"], SERIES_LINESTYLES["observed"], "Observed", 0.15),
            (ddef, dc, SERIES_COLORS["default"], SERIES_LINESTYLES["default"], "Default (modified STARFIT)", 0.10),
            (ndf, nc, SERIES_COLORS["parametric"], SERIES_LINESTYLES["parametric"], "Simulation (optimized)", 0.10),
        ]:
            q = df.groupby("doy")[col].quantile([0.1, 0.5, 0.9]).unstack().reindex(range(1, 367))
            ax.fill_between(
                q.index.values,
                q[0.1].values,
                q[0.9].values,
                color=color,
                alpha=a,
                label=f"{lbl} 10-90%",
            )
            ax.plot(q.index.values, q[0.5].values, color=color, ls=ls, lw=2.0, label=f"{lbl} median")
        ax.set_title(ttl)
        ax.set_xlabel("Day of year")
        ax.set_ylabel(ylab)
        ax.set_xlim(1, 366)
        ax.grid(alpha=0.3)

    handles, labels = axS.get_legend_handles_labels()
    fig.legend(handles, labels, loc="lower center", ncol=3, fontsize=8)
    fig.suptitle(title_prefix + " — Seasonal multi-panel v2 (shaded 10-90% + median)")
    fig.tight_layout(rect=(0, 0.11, 1, 1))
    fig.savefig(save_path, dpi=180, bbox_inches="tight")
    plt.close(fig)


def plot_trenton_timeseries_and_fdc(obs: pd.Series | None,
                                    sim_dict: dict[str, pd.Series],
                                    title_prefix: str,
                                    save_path: str,
                                    min_flow_target: pd.Series | None = None):
    fig, axes = plt.subplots(2, 1, figsize=(12, 8), sharex=False)
    ax_ts, ax_fdc = axes

    if min_flow_target is not None and len(min_flow_target):
        m = min_flow_target.astype(float).dropna()
        if len(m):
            ax_ts.plot(
                m.index, m.values,
                color="#c0392b",
                ls=":",
                lw=1.6,
                label="Min. flow target (Trenton, Pywr-DRB)",
                zorder=8,
            )
    if obs is not None and len(obs):
        ax_ts.plot(
            obs.index, obs.values,
            color=SERIES_COLORS["observed"],
            ls=SERIES_LINESTYLES["observed"],
            lw=SERIES_LINEWIDTHS["observed"],
            label="Observed",
        )
        x, y = _fdc_xy(obs)
        if x is not None:
            ax_fdc.plot(
                x, y,
                color=SERIES_COLORS["observed"],
                ls=SERIES_LINESTYLES["observed"],
                lw=SERIES_LINEWIDTHS["observed"],
                label="Observed",
            )

    palette = {
        "Pywr Default": SERIES_COLORS["default"],
        "Independent": SERIES_COLORS["independent"],
    }
    linestyle_map = {
        "Pywr Default": SERIES_LINESTYLES["default"],
        "Independent": SERIES_LINESTYLES["independent"],
    }
    for name, ser in sim_dict.items():
        if ser is None or len(ser) == 0:
            continue
        n = str(name).lower()
        if "parametric" in n:
            c = get_parametric_color("perfect_foresight" if "perfect" in n else ("regression_disagg" if "regression" in n else None))
            ls = SERIES_LINESTYLES["parametric"]
        else:
            c = palette.get(name, SERIES_COLORS["parametric"])
            ls = linestyle_map.get(name, SERIES_LINESTYLES["parametric"])
        ax_ts.plot(ser.index, ser.values, lw=SERIES_LINEWIDTHS["parametric"], ls=ls, label=name, color=c)
        x, y = _fdc_xy(ser)
        if x is not None:
            ax_fdc.plot(x, y, lw=SERIES_LINEWIDTHS["parametric"], ls=ls, label=name, color=c)

    ax_ts.set_title(f"{title_prefix} — Trenton flow")
    ax_ts.set_ylabel("Flow (MGD)")
    ax_ts.set_xlabel("Date")
    ax_ts.grid(alpha=0.3)
    ax_ts.legend(loc="upper right", fontsize=8)

    ax_fdc.set_title("Trenton flow FDC")
    ax_fdc.set_xlabel("Exceedance probability (%)")
    ax_fdc.set_ylabel("Flow (MGD)")
    ax_fdc.grid(alpha=0.3)
    ax_fdc.legend(loc="upper right", fontsize=8)

    fig.tight_layout()
    fig.savefig(save_path, dpi=180, bbox_inches="tight")
    plt.close(fig)


def plot_lower_basin_mrf_compare(mrf_param: pd.DataFrame | None,
                                 mrf_default: pd.DataFrame | None,
                                 title_prefix: str,
                                 save_path: str,
                                 line_width: float = 2.2):
    cols = [
        "mrf_trenton_beltzvilleCombined",
        "mrf_trenton_blueMarsh",
        "mrf_trenton_nockamixon",
    ]
    labels = ["Beltzville Combined", "Blue Marsh", "Nockamixon"]

    nrows = 2 if mrf_default is not None else 1
    fig, axes = plt.subplots(nrows, 1, figsize=(14, 4 * nrows), sharex=True)
    if nrows == 1:
        axes = [axes]

    def _stack(ax, df, title):
        if df is None or any(c not in df.columns for c in cols):
            ax.text(0.5, 0.5, "Required lower-basin contribution columns not found", ha="center", va="center", transform=ax.transAxes)
            ax.set_title(title)
            return
        ax.stackplot(
            df.index,
            df[cols[0]].astype(float),
            df[cols[1]].astype(float),
            df[cols[2]].astype(float),
            labels=labels,
            alpha=0.8,
            linewidth=line_width,
            edgecolor="white",
        )
        ax.set_title(title)
        ax.set_ylabel("Contribution (MGD)")
        ax.grid(alpha=0.3)
        ax.legend(loc="upper left", fontsize=8)

    _stack(axes[0], mrf_param, f"{title_prefix} — lower-basin MRF (parametric)")
    if mrf_default is not None:
        _stack(axes[1], mrf_default, "Lower-basin MRF (default)")
        axes[1].set_xlabel("Date")
    else:
        axes[0].set_xlabel("Date")

    fig.tight_layout()
    fig.savefig(save_path, dpi=180, bbox_inches="tight")
    plt.close(fig)

# unified default picks (legacy + advanced); must match columns in Borg CSVs / OBJ_LABELS
DEFAULT_PICKS = list(DEFAULT_STAGE1_PICKS)


# ---------- load BORG and build legacy+advanced picks ----------
def load_picks_with_advanced():
    res2pol2_obj = {}
    res2pol2_var = {}
    res2pol2_candmap = {}

    for res in reservoir_options:
        res2pol2_obj[res] = {}
        res2pol2_var[res] = {}
        res2pol2_candmap[res] = {}
        for pol in policy_type_options:
            fname = resolve_borg_moea_csv_path(pol, res)
            try:
                obj_df, var_df = load_results(
                    fname, obj_labels=OBJ_LABELS, filter=True, obj_bounds=OBJ_FILTER_BOUNDS
                )
            except Exception as e:
                print(f"[SEL] Skip {res}/{pol}: failed to load ({e}).")
                continue
            if obj_df is None or len(obj_df) == 0:
                print(f"[SEL] Skip {res}/{pol}: no solutions.")
                continue

            # ---- legacy highlights (aligned with OBJ_LABELS / stage1) ----
            idx_best_release = obj_df["Release NSE"].idxmax()
            idx_best_storage = obj_df["Storage NSE"].idxmax()
            idx_best_average = obj_df[["Release NSE", "Storage NSE"]].mean(axis=1).idxmax()

            min_obj = obj_df.copy()
            min_obj["Release NSE"] = -min_obj["Release NSE"]
            min_obj["Storage NSE"] = -min_obj["Storage NSE"]
            scaled = (min_obj - min_obj.min()) / (min_obj.max() - min_obj.min())
            idx_best_all_avg = _idxmin_safe(scaled.mean(axis=1))

            highlight = {
                idx_best_release: RELEASE_NSE_OBJECTIVE_OPTIMUM,
                idx_best_storage: STORAGE_NSE_OBJECTIVE_OPTIMUM,
                idx_best_average: AVERAGE_NSE_OBJECTIVE_OPTIMUM,
                idx_best_all_avg: BEST_AVERAGE_ALL,
            }
            obj_df = obj_df.copy()
            obj_df["highlight"] = ["Other"] * len(obj_df)
            for i, lab in highlight.items():
                if i in obj_df.index:
                    obj_df.loc[i, "highlight"] = lab

            # ---- advanced highlights (same objectives as stage1 / config) ----
            advanced_objectives = list(OBJ_LABELS.values())
            obj_df_aug, cand_df, cand_map = compute_and_apply_advanced_highlights(
                obj_df,
                objectives=advanced_objectives,
                senses=SENSES_ALL,
                bounds=OBJ_FILTER_BOUNDS,
                eps_qs=(0.5, 0.8),
                add_k_diverse=2,
                include_hv=False,
                out_label_col="highlight_adv",
            )

            res2pol2_obj[res][pol] = obj_df_aug
            res2pol2_var[res][pol] = var_df
            res2pol2_candmap[res][pol] = cand_map

    return res2pol2_obj, res2pol2_var, res2pol2_candmap


def get_pick_indices(solution_objs, cand_maps, reservoir_name: str, policy_type: str, label: str):
    """
    Return list of row indices for requested pick, searching:
      1) legacy 'highlight' column
      2) advanced cand_map entries
      3) 'highlight_adv' column
    Legacy pick names are accepted via :func:`normalize_pick_label`.
    """
    out = []

    df = solution_objs.get(reservoir_name, {}).get(policy_type)
    cand_map = (cand_maps.get(reservoir_name, {}) or {}).get(policy_type, {}) or {}

    if df is not None and "highlight" in df.columns:
        for lbl in iter_pick_lookup_labels(label):
            out += df.index[df["highlight"] == lbl].tolist()

    val = resolve_cand_map_value(cand_map, label)
    if val is not None:
        if isinstance(val, (list, tuple, np.ndarray, pd.Index, pd.Series)):
            out += list(pd.Index(val))
        else:
            out.append(val)

    if df is not None and "highlight_adv" in df.columns:
        for lbl in iter_pick_lookup_labels(label):
            out += df.index[df["highlight_adv"] == lbl].tolist()

    # dedupe preserving order
    seen, deduped = set(), []
    for idx in out:
        key = int(idx) if isinstance(idx, (int, np.integer)) or str(idx).isdigit() else idx
        if key not in seen:
            seen.add(key)
            deduped.append(idx)
    return deduped


# ---------- pywr runs ----------
def build_release_policy_dict_and_row_ids(
    sol_vars,
    sol_objs,
    cand_maps,
    reservoirs,
    pol,
    pick,
    require_all_reservoirs: bool = True,
):
    """
    Build ``release_policy_dict`` for *all* ``reservoirs`` for one (policy, pick), plus Borg row
    labels / ilocs for metadata (JSON + HDF5 attrs).

    Returns ``(release_policy_dict, row_index_labels_by_reservoir, row_iloc_by_reservoir)``.
    When ``require_all_reservoirs`` is True, returns ``(None, None, None)`` if any
    requested reservoir lacks this pick. When False, includes only available reservoirs
    and returns ``(None, None, None)`` only if none are available.
    """
    release_policy_dict = {}
    row_labels: dict = {}
    row_ilocs: dict = {}
    for res in reservoirs:
        if res not in sol_objs or pol not in sol_objs.get(res, {}):
            if require_all_reservoirs:
                return None, None, None
            continue
        idxs = get_pick_indices(sol_objs, cand_maps, res, pol, pick)
        if not idxs:
            if require_all_reservoirs:
                return None, None, None
            continue
        var_df = sol_vars[res][pol]
        idx0 = idxs[0]
        params = var_df.loc[idx0].values
        release_policy_dict[res] = {
            "class_type": "ParametricReservoirRelease",
            "policy_type": pol,
            "policy_id": "inline",
            "params": ",".join(str(x) for x in np.asarray(params, float).tolist()),
        }
        row_labels[res] = normalize_borg_row_label(idx0)
        try:
            loc = var_df.index.get_loc(idx0)
            if isinstance(loc, slice):
                row_ilocs[res] = int(loc.start)
            elif isinstance(loc, (np.ndarray, list)):
                row_ilocs[res] = int(loc[0]) if len(loc) else None
            else:
                row_ilocs[res] = int(loc)
        except Exception:
            pass
    if not release_policy_dict:
        return None, None, None
    return release_policy_dict, row_labels, row_ilocs


def build_release_policy_dict_for_pick(sol_vars, sol_objs, cand_maps, reservoirs, pol, pick):
    """
    Build ``release_policy_dict`` for *all* ``reservoirs`` for one (policy, pick), matching stage1's
    combined Pywr run (FE Walter, Prompton, Beltzville, Blue Marsh, … in one model).
    Returns None if any reservoir lacks that pick.
    """
    rdict, _, _ = build_release_policy_dict_and_row_ids(sol_vars, sol_objs, cand_maps, reservoirs, pol, pick)
    return rdict


# Re-export for callers that imported from ``figures_validation``:
_parametric_result_from_h5_path = parametric_result_from_h5_path


def _tuple_for_res(multi_result: dict, res_name: str):
    """Map multi-res cache entry to the legacy 6-tuple for one reservoir."""
    br0, br1 = multi_result["by_res"][res_name]
    return (
        br0,
        br1,
        multi_result["trenton"],
        multi_result["mrf"],
        multi_result["obs_trenton"],
        multi_result["mrf_target_trenton"],
    )


def run_pywr_default(start, end, inflow_type, work_dir, flow_prediction_mode: str | None = None):
    """Build & run default model. Returns (dfD_R_dict, dfD_S_dict) for all reservoirs or (None, None) on failure."""
    if flow_prediction_mode is None:
        flow_prediction_mode = _default_pywr_flow_mode()
    try:
        os.makedirs(work_dir, exist_ok=True)
        mb_def = pywrdrb.ModelBuilder(
            start_date=start,
            end_date=end,
            inflow_type=inflow_type,
            options={"flow_prediction_mode": flow_prediction_mode},
        )
        mb_def.make_model()
        model_def_json = os.path.join(work_dir, "model_default.json")
        mb_def.write_model(model_def_json)
        model_def = pywrdrb.Model.load(model_def_json)
        h5_def = os.path.join(work_dir, "output_default.hdf5")
        _ = pywrdrb.OutputRecorder(model_def, h5_def)
        _ = model_def.run()

        results_sets = ["major_flow", "res_storage", "reservoir_downstream_gage", "lower_basin_mrf_contributions"]
        dataD = pywrdrb.Data(print_status=False, results_sets=results_sets, output_filenames=[h5_def])
        dataD.load_output()
        with warnings.catch_warnings():
            warnings.filterwarnings(
                "ignore",
                message="Resampling with a PeriodIndex is deprecated.*",
                category=FutureWarning,
            )
            dataD.load_observations()
        kD = os.path.splitext(os.path.basename(h5_def))[0]

        dfD_R = {
            res: dataD.reservoir_downstream_gage[kD][0][res].astype(float).rename("default_release")
            for res in reservoir_options
            if res in dataD.reservoir_downstream_gage[kD][0].columns
        }
        dfD_S = {
            res: dataD.res_storage[kD][0][res].astype(float).rename("default_storage")
            for res in reservoir_options
            if res in dataD.res_storage[kD][0].columns
        }
        dfD_T = (
            dataD.major_flow[kD][0]["delTrenton"].astype(float).rename("default_trenton")
            if "delTrenton" in dataD.major_flow[kD][0].columns
            else None
        )
        dfD_MRF = dataD.lower_basin_mrf_contributions[kD][0].copy() if kD in dataD.lower_basin_mrf_contributions else None
        return dfD_R, dfD_S, dfD_T, dfD_MRF
    except Exception as e:
        print(f"[WARN] Default Pywr run failed; continuing without default series. Reason: {e}")
        return None, None, None, None


# ---------- main ----------
def main(argv=None):
    """Run validation figures.

    When ``argv`` is ``None`` (default), arguments are taken from ``sys.argv[1:]`` (CLI).
    The orchestrator ``04_make_figures.py`` calls ``main([])`` so top-level flags like
    ``--figures`` / ``--skip-stage1`` are not passed here; use ``CEE_FIGURE_NUMBERS`` and
    other env vars set by that script.
    """
    if argv is None:
        argv = sys.argv[1:]
    ap = argparse.ArgumentParser()
    ap.add_argument("--reservoirs", nargs="*", default=reservoir_options,
                    help="subset like: fewalter prompton blueMarsh beltzvilleCombined")
    ap.add_argument("--policies", nargs="*", default=policy_type_options, choices=["STARFIT","RBF","PWL"])
    ap.add_argument("--picks", nargs="*", default=DEFAULT_PICKS,
                    help="Will match both legacy 'highlight' and advanced 'highlight_adv' / cand_map.")
    ap.add_argument("--val-start", default="1980-01-01")
    ap.add_argument("--val-end",   default="2018-12-31")
    ap.add_argument(
        "--plot-start",
        default=None,
        help="Optional: override plot window start (YYYY-MM-DD). If set, also set --plot-end.",
    )
    ap.add_argument(
        "--plot-end",
        default=None,
        help="Optional: override plot window end (YYYY-MM-DD).",
    )
    ap.add_argument(
        "--mrf-fivepanel-style",
        choices=("rolling", "bar_monthly"),
        default="rolling",
        help="Panel 4 style for lower-basin MRF contributions.",
    )
    ap.add_argument("--mrf-rolling-days", type=int, default=7)
    ap.add_argument("--skip-fivepanel", action="store_true", help="Skip 5-panel lower-basin MRF figure.")
    ap.add_argument(
        "--skip-error-ts-release-multi",
        action=argparse.BooleanOptionalAction,
        default=False,
        help="Skip Figure 8 combined release diagnostics (time series + error vs flow percentile + seasonal "
        "2×2). Default: generate them. Pass --skip-error-ts-release-multi to skip (faster validation).",
    )
    ap.add_argument(
        "--mrf-overlap-only",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Restrict lower-basin MRF figures to overlapping non-NA date range (default: on).",
    )
    ap.add_argument(
        "--mrf-line-width",
        type=float,
        default=2.2,
        help="Line width styling for lower-basin MRF contribution boundaries/curves.",
    )
    ap.add_argument("--dynamics-line-width", type=float, default=1.35)
    ap.add_argument("--dynamics-downsample", type=int, default=1, help="1 = no downsampling.")
    ap.add_argument("--no-dynamics-nse", action="store_true", help="Hide release NSE text column on 2x1 dynamics.")
    ap.add_argument(
        "--pywr-start",
        default=None,
        metavar="YYYY-MM-DD",
        help="Pywr timestepper start (omit with --pywr-end to use model_date_ranges for --pywr-inflow-type).",
    )
    ap.add_argument(
        "--pywr-end",
        default=None,
        metavar="YYYY-MM-DD",
        help="Pywr timestepper end (omit with --pywr-start to use model_date_ranges for --pywr-inflow-type).",
    )
    ap.add_argument(
        "--pywr-inflow-type",
        default="pub_nhmv10_BC_withObsScaled",
        help="Used with default Pywr dates from pywrdrb.utils.dates.model_date_ranges when --pywr-* omitted.",
    )
    ap.add_argument(
        "--pywr-flow-prediction-mode",
        default="auto",
        choices=("auto", "regression_disagg", "perfect_foresight", "gage_flow"),
        help=(
            "ModelBuilder Options.flow_prediction_mode. "
            "'auto' uses CEE_PYWR_FLOW_PREDICTION_MODE if set, else regression_disagg."
        ),
    )
    ap.add_argument("--use-opt-window", action="store_true",
                    help="Plot strictly on the optimization (inflow_pub) window.")
    ap.add_argument("--align-inflow", action="store_true",
                    help="Force 'pub_nhmv10_BC_withObsScaled' for the Pywr-DRB runs.")
    ap.add_argument("--skip-default-run", action="store_true",
                    help="Do not build/run Pywr default model (avoids STARFIT CSV dependency).")
    ap.add_argument(
        "--outdir",
        default=None,
        help="Figure root directory (default: resolve_figure_root(FIG_DIR); subfolders fig5_* … are created there).",
    )
    ap.add_argument("--save-series", action="store_true")
    ap.add_argument("--compare-series", action="store_true")
    ap.add_argument("--rtol", type=float, default=0.0)
    ap.add_argument("--atol", type=float, default=0.0)
    argv_list = list(argv)
    args = ap.parse_args(argv)
    # Match stage 1: when ``CEE_DESIRED_PICKS`` / ``CEE_FIGURE_POLICIES`` are set (typical for ``04_make_figures.py``),
    # use them unless the caller passed explicit ``--picks`` / ``--policies``.
    if "--picks" not in argv_list:
        args.picks = _figure_picks_from_env()
    else:
        args.picks = [normalize_pick_label(p) for p in args.picks]
    if "--policies" not in argv_list:
        args.policies = _figure_policies_from_env()

    _effective_pywr_inflow = (
        "pub_nhmv10_BC_withObsScaled" if args.align_inflow else args.pywr_inflow_type
    )
    try:
        pywr_run_start, pywr_run_end = _resolve_pywr_simulation_dates(
            _effective_pywr_inflow,
            args.pywr_start,
            args.pywr_end,
        )
    except KeyError as exc:
        raise SystemExit(str(exc)) from exc

    def _resolved_pywr_flow_mode() -> str:
        if args.pywr_flow_prediction_mode != "auto":
            return args.pywr_flow_prediction_mode
        return _default_pywr_flow_mode()

    def _parametric_modes_to_run() -> tuple[str, ...]:
        """Only run basin Pywr for modes that will be plotted (not both regression + PFI every time)."""
        pm = _resolved_pywr_flow_mode()
        if pm in ("regression_disagg", "perfect_foresight"):
            return (pm,)
        return ("regression_disagg", "perfect_foresight")

    _vf = _parse_figure_numbers()

    def _v(n):
        return _want_figure(n, _vf)

    if _vf is not None and _vf.isdisjoint({7, 8, 10, 11}):
        print("[validate] CEE_FIGURE_NUMBERS excludes figures 7–8 and 10–11 — skipping validation stage.")
        print("DONE.")
        return

    fig_root = args.outdir or resolve_figure_root(FIG_DIR)
    outdir = ensure_dir(fig_root)
    pywr_work_dir = ensure_dir(get_pywr_work_dir())
    print(f"[paths] Pywr model JSON/HDF5 -> {pywr_work_dir} (set CEE_PYWR_WORK_DIR to override)")
    outdir_dyn = ensure_dir(os.path.join(outdir, "fig07_validation_dynamics"))
    outdir_five = ensure_dir(os.path.join(outdir, "fig12_lower_basin_context"))
    outdir_fig6 = ensure_dir(os.path.join(outdir, "fig08_error_vs_flow_percentile"))
    outdir_release_dist = ensure_dir(os.path.join(outdir, "fig09_release_distribution"))
    outdir_opspace = ensure_dir(os.path.join(outdir, "fig10_operational_space"))
    outdir_seasonal = ensure_dir(os.path.join(outdir, "fig11_seasonal_multipanel"))
    trenton_folder = ensure_dir(os.path.join(outdir, "fig13_trenton_flow"))

    print(f"[info] writing under figure root: {outdir}")
    print(f"[validate] focal picks ({len(args.picks)}): {args.picks}")
    print(f"[validate] policies ({len(args.policies)}): {args.policies}")
    _param_modes = _parametric_modes_to_run()
    print(f"[validate] parametric Pywr flow mode(s) to run: {_param_modes} (resolved active: {_resolved_pywr_flow_mode()!r})")
    _fpm = _resolved_pywr_flow_mode()
    print(f"[pywr] ModelBuilder flow_prediction_mode={_fpm!r} (CLI --pywr-flow-prediction-mode or auto)")
    print(f"[pywr] pywrdrb package: {pywrdrb.__file__}")
    if args.pywr_start is None and args.pywr_end is None:
        print(
            f"[pywr] simulation window {pywr_run_start} → {pywr_run_end} "
            f"(model_date_ranges[{_effective_pywr_inflow!r}])"
        )
    else:
        print(f"[pywr] simulation window {pywr_run_start} → {pywr_run_end} (--pywr-start/--pywr-end)")

    # compute the optimization (public) window per-reservoir
    def _opt_window_for_res(res):
        inflow_pub_df, release_pub_df, storage_pub_df = get_observational_training_data(
            reservoir_name=res, data_dir=PROCESSED_DATA_DIR, as_numpy=False, inflow_type="inflow_pub"
        )
        idx = inflow_pub_df.index
        return str(idx.min().date()), str(idx.max().date())

    # 1) load results + advanced picks
    sol_objs, sol_vars, cand_maps = load_picks_with_advanced()

    print_policy_row_counts(sol_objs, list(policy_type_options), label="validate")

    # 1b) Pre-run combined parametric Pywr (one HDF5 per policy × pick × flow mode).
    # Use exactly the four MOEA parametric nodes in one release_policy_dict — not args.reservoirs
    # (which may list the whole basin). Never one Pywr run per reservoir for the same pick.
    parametric_cache: dict = {}
    for pol in args.policies:
        for pick in args.picks:
            rdict, row_labels, row_ilocs = build_release_policy_dict_and_row_ids(
                sol_vars,
                sol_objs,
                cand_maps,
                list(PARAMETRIC_MOEA_RESERVOIR_KEYS),
                pol,
                pick,
                require_all_reservoirs=False,
            )
            if rdict is None:
                print(
                    f"[validate] No release_policy_dict for {pol}/{pick!r} "
                    f"(no available reservoirs for this pick in {list(PARAMETRIC_MOEA_RESERVOIR_KEYS)})."
                )
                continue
            for mode_name in _parametric_modes_to_run():
                key = (pol, pick, mode_name)
                if key in parametric_cache:
                    continue
                stem_base = parametric_hdf5_stem(
                    pol, pick, mode_name, _effective_pywr_inflow
                )
                pywr_run_metadata = {
                    "pick_label": pick,
                    "policy_type": pol,
                    "row_index_labels_by_reservoir": row_labels,
                    "row_indices_by_reservoir": row_ilocs if row_ilocs else None,
                }
                try:
                    parametric_cache[key] = run_pywr_parametric_multi(
                        rdict,
                        pywr_run_start,
                        pywr_run_end,
                        _effective_pywr_inflow,
                        pywr_work_dir,
                        stem_base,
                        mode_name,
                        pywr_run_metadata=pywr_run_metadata,
                    )
                except Exception as e:
                    print(f"[WARN] multi-reservoir Pywr failed for {pol} / {pick!r} / {mode_name}: {e}")

    # 2) (optional) run Pywr default ONCE and cache results (under pywr work dir, not figure folders)
    def_R_all, def_S_all, def_T_all, def_MRF_all = (None, None, None, None)
    if not args.skip_default_run:
        def_R_all, def_S_all, def_T_all, def_MRF_all = run_pywr_default(
            pywr_run_start,
            pywr_run_end,
            _effective_pywr_inflow,
            pywr_work_dir,
            flow_prediction_mode=_resolved_pywr_flow_mode(),
        )

    # 3) loop reservoirs/policies/picks
    for res in args.reservoirs:
        pywr_start, pywr_end = pywr_run_start, pywr_run_end
        pywr_inflow_type = _effective_pywr_inflow

        if res not in sol_objs:
            print(f"[Skip] {res}: no results dict."); continue

        # choose the PLOT window
        if args.plot_start is not None and args.plot_end is not None:
            PLOT_START, PLOT_END = args.plot_start, args.plot_end
            print(f"[plot-window] {res}: {PLOT_START} → {PLOT_END} (--plot-start/--plot-end)")
        elif args.use_opt_window:
            PLOT_START, PLOT_END = _opt_window_for_res(res)
            print(f"[plot-window] {res}: {PLOT_START} → {PLOT_END} (optimization window)")
        else:
            PLOT_START, PLOT_END = args.val_start, args.val_end
            print(f"[plot-window] {res}: {PLOT_START} → {PLOT_END} (--val-start/--val-end)")
        plot_slicer = slice(PLOT_START, PLOT_END)
        date_tag = figure_date_tag(PLOT_START, PLOT_END)

        # observed series for the plot window
        inflow_df, release_df, storage_df = get_observational_training_data(
            reservoir_name=res, data_dir=PROCESSED_DATA_DIR, as_numpy=False, inflow_type="inflow_pub"
        )
        obs_release = (release_df.loc[plot_slicer][res] if res in release_df.columns else None)
        obs_storage = (storage_df.loc[plot_slicer][res] if res in storage_df.columns else storage_df.loc[plot_slicer].iloc[:,0])

        for pol in args.policies:
            if pol not in sol_objs.get(res, {}):
                print(f"[Skip] {res}/{pol}: no solutions."); continue

            obj_df = sol_objs[res][pol]
            var_df = sol_vars[res][pol]

            for pick in args.picks:
                idxs = get_pick_indices(sol_objs, cand_maps, res, pol, pick)
                if not idxs:
                    print(f"[Skip] {res}/{pol}/{pick}: not found."); continue
                # take first match
                params = var_df.loc[idxs[0]].values

                # Independent run on full inflow_pub index; slice to plot window
                inflow_df2, release_df2, storage_df2 = get_observational_training_data(
                    reservoir_name=res, data_dir=PROCESSED_DATA_DIR, as_numpy=False, inflow_type="inflow_pub"
                )
                dt_idx = inflow_df2.index
                inflow = inflow_df2[res].to_numpy().astype(float).ravel()

                indie = Reservoir(
                    inflow=inflow, dates=dt_idx, capacity=float(reservoir_capacity[res]),
                    policy_type=pol, policy_params=params, name=res
                )
                indie.reset(); indie.run()
                indie_S = pd.Series(indie.storage_array.flatten(), index=dt_idx, name=res).loc[plot_slicer]
                indie_R = pd.Series((indie.release_array + indie.spill_array).flatten(), index=dt_idx, name=res).loc[plot_slicer]

                try:
                    pnames = get_param_names_for_policy(pol)
                    pv = np.asarray(params, dtype=float).ravel()
                    k = min(len(pnames), len(pv))
                    param_lines = [f"{pnames[i]}={pv[i]:.6g}" for i in range(k)]
                    param_text = "Parameters:\n" + "\n".join(param_lines)
                except Exception:
                    param_text = "Parameters:\n" + ", ".join(f"{float(x):.6g}" for x in np.asarray(params, float).ravel())

                # Pywr parametric: slice series from the single combined run per (policy, pick, mode)
                # (all four MOEA reservoirs in one ModelBuilder run — no per-reservoir fallback).
                mode_runs = {}
                for mode_name in _parametric_modes_to_run():
                    mkey = (pol, pick, mode_name)
                    try:
                        if mkey not in parametric_cache:
                            print(
                                f"[WARN] Missing combined parametric cache {mkey} — "
                                f"pre-run may have failed for this pick."
                            )
                            continue
                        if res not in parametric_cache[mkey]["by_res"]:
                            print(
                                f"[Skip] {res}/{pol}/{pick}/{mode_name}: reservoir is not a parametric node "
                                f"in the combined model (nodes: {list(parametric_cache[mkey]['by_res'].keys())})."
                            )
                            continue
                        r, s, t, mrf, obs_t, trenton_tgt = _tuple_for_res(parametric_cache[mkey], res)
                        mode_runs[mode_name] = (
                            r.loc[plot_slicer],
                            s.loc[plot_slicer],
                            t.loc[plot_slicer] if t is not None else None,
                            mrf.loc[plot_slicer] if mrf is not None else None,
                            obs_t.loc[plot_slicer] if obs_t is not None else None,
                            trenton_tgt.loc[plot_slicer] if trenton_tgt is not None else None,
                        )
                    except Exception as e:
                        print(f"[WARN] Pywr parametric mode '{mode_name}' failed for {res}/{pol}/{pick}: {e}")

                active_mode = _resolved_pywr_flow_mode()
                if active_mode not in mode_runs and mode_runs:
                    active_mode = next(iter(mode_runs.keys()))
                if active_mode not in mode_runs:
                    print(f"[Skip] {res}/{pol}/{pick}: no successful parametric Pywr modes.")
                    continue

                flow_mode_label = active_mode
                param_series_label = f"Pywr-DRB Parametric ({flow_mode_label})"
                pywr_Rv, pywr_Sv, pywr_Tv, pywr_MRFv, obs_Tv, trenton_target_v = mode_runs[active_mode]

                # default series (if available)
                def_Rv = def_Sv = None
                if def_R_all is not None and res in def_R_all:
                    def_Rv = def_R_all[res].loc[plot_slicer]
                if def_S_all is not None and res in def_S_all:
                    def_Sv = def_S_all[res].loc[plot_slicer]
                def_Tv = def_T_all.loc[plot_slicer] if def_T_all is not None else None
                def_MRFv = def_MRF_all.loc[plot_slicer] if def_MRF_all is not None else None

                # Figure 7: 2×1 dynamics + release FDC + NSE/params (focused slices)
                if _v(7):
                    windows = [
                        ("drought_2010_2012", "2010-01-01", "2012-12-31"),
                        ("normal_2012_2014", "2012-01-01", "2014-12-31"),
                    ]
                    for win_name, ws, we in windows:
                        w = slice(ws, we)
                        iR_w, pR_w, dR_w = indie_R.loc[w], pywr_Rv.loc[w], (def_Rv.loc[w] if def_Rv is not None else None)
                        iS_w, pS_w, dS_w = indie_S.loc[w], pywr_Sv.loc[w], (def_Sv.loc[w] if def_Sv is not None else None)
                        oR_w = obs_release.loc[w] if obs_release is not None else None
                        oS_w = obs_storage.loc[w] if obs_storage is not None else None
                        fig7_start, fig7_end = _effective_plot_window(
                            [iR_w, pR_w, dR_w, oR_w, iS_w, pS_w, dS_w, oS_w],
                            ws,
                            we,
                        )
                        dyn_png = os.path.join(
                            outdir_dyn,
                            f"{res}_{pol}_{pick_filename_slug(pick)}_2x1_dynamics_fdc_{figure_date_tag(fig7_start, fig7_end)}_{win_name}.png",
                        )
                        plot_2x1_dynamics(
                            reservoir=res,
                            policy=pol,
                            indie_R=iR_w,
                            indie_S=iS_w,
                            pywr_R=pR_w,
                            pywr_S=pS_w,
                            def_R=dR_w,
                            def_S=dS_w,
                            obs_R=oR_w,
                            obs_S=oS_w,
                            date_label=f"{fig7_start} to {fig7_end}",
                            ylims_storage=None,
                            ylims_release=None,
                            save_path=dyn_png,
                            yscale_storage=None,
                            yscale_release=None,
                            max_date_ticks=10,
                            downsample_step=args.dynamics_downsample,
                            line_width=args.dynamics_line_width,
                            pick_label=str(pick),
                            param_text=param_text,
                            show_release_nse_panel=not args.no_dynamics_nse,
                            add_release_fdc_panel=True,
                            parametric_label=param_series_label,
                        )
                        if pol == "STARFIT":
                            lo366, hi366 = try_compute_starfit_nor_pct_by_doy(params, res)
                            if lo366 is not None:
                                nor_lo_s, nor_hi_s = nor_pct_series_on_index(iR_w.index, lo366, hi366)
                                dyn_png_7a = os.path.join(
                                    outdir_dyn,
                                    f"{res}_{pol}_{pick_filename_slug(pick)}_2x1_dynamics_fdc_{figure_date_tag(fig7_start, fig7_end)}_{win_name}_pct_nor.png",
                                )
                                plot_2x1_dynamics(
                                    reservoir=res,
                                    policy=pol,
                                    indie_R=iR_w,
                                    indie_S=iS_w,
                                    pywr_R=pR_w,
                                    pywr_S=pS_w,
                                    def_R=dR_w,
                                    def_S=dS_w,
                                    obs_R=oR_w,
                                    obs_S=oS_w,
                                    date_label=f"{fig7_start} to {fig7_end}",
                                    ylims_storage=None,
                                    ylims_release=None,
                                    save_path=dyn_png_7a,
                                    yscale_storage=None,
                                    yscale_release=None,
                                    max_date_ticks=10,
                                    downsample_step=args.dynamics_downsample,
                                    line_width=args.dynamics_line_width,
                                    pick_label=str(pick),
                                    param_text=param_text,
                                    show_release_nse_panel=not args.no_dynamics_nse,
                                    add_release_fdc_panel=True,
                                    storage_as_pct_capacity=True,
                                    capacity_mg=float(reservoir_capacity[res]),
                                    nor_lo_pct=nor_lo_s,
                                    nor_hi_pct=nor_hi_s,
                                    parametric_label=param_series_label,
                                )

                # New validation-focused diagnostics (distribution, op-space, seasonal)
                if _v(8):
                    if obs_release is not None and def_Rv is not None:
                        pfx = f"{res} {pol} {pick}"
                        plot_release_distribution_diagnostics(
                            obs_release=obs_release,
                            default_release=def_Rv,
                            new_release=pywr_Rv,
                            title_prefix=pfx,
                            save_path=os.path.join(outdir_release_dist, f"{res}_{pol}_{pick_filename_slug(pick)}_release_dist_{date_tag}.png"),
                        )
                    if obs_release is not None and def_Rv is not None and def_Sv is not None and obs_storage is not None:
                        plot_operational_space(
                            obs_storage_mg=obs_storage,
                            obs_release=obs_release,
                            default_storage_mg=def_Sv,
                            default_release=def_Rv,
                            new_storage_mg=pywr_Sv,
                            new_release=pywr_Rv,
                            capacity_mg=float(reservoir_capacity[res]),
                            title_prefix=f"{res} {pol} {pick}",
                            save_path=os.path.join(outdir_opspace, f"{res}_{pol}_{pick_filename_slug(pick)}_operational_space_{date_tag}.png"),
                        )
                        plot_seasonal_multipanel(
                            obs_storage_mg=obs_storage,
                            obs_release=obs_release,
                            default_storage_mg=def_Sv,
                            default_release=def_Rv,
                            new_storage_mg=pywr_Sv,
                            new_release=pywr_Rv,
                            capacity_mg=float(reservoir_capacity[res]),
                            title_prefix=f"{res} {pol} {pick}",
                            save_path=os.path.join(outdir_seasonal, f"{res}_{pol}_{pick_filename_slug(pick)}_seasonal_doy_{date_tag}.png"),
                        )
                        plot_seasonal_multipanel_v2_ranges(
                            obs_storage_mg=obs_storage,
                            obs_release=obs_release,
                            default_storage_mg=def_Sv,
                            default_release=def_Rv,
                            new_storage_mg=pywr_Sv,
                            new_release=pywr_Rv,
                            capacity_mg=float(reservoir_capacity[res]),
                            title_prefix=f"{res} {pol} {pick}",
                            save_path=os.path.join(outdir_seasonal, f"{res}_{pol}_{pick_filename_slug(pick)}_seasonal_doy_v2_ranges_{date_tag}.png"),
                        )

                if _v(10) and not args.skip_fivepanel:
                    windows = [
                        ("drought_2010_2012", "2010-01-01", "2012-12-31"),
                        ("normal_2012_2014", "2012-01-01", "2014-12-31"),
                    ]
                    base_overlap = pd.Index(obs_storage.dropna().index)
                    if obs_release is not None:
                        base_overlap = base_overlap.intersection(obs_release.dropna().index)
                    if pywr_Tv is not None:
                        base_overlap = base_overlap.intersection(pywr_Tv.dropna().index)
                    if obs_Tv is not None:
                        base_overlap = base_overlap.intersection(obs_Tv.dropna().index)
                    if pywr_MRFv is not None and len(pywr_MRFv) > 0:
                        mrf_rows = pywr_MRFv.dropna(how="all")
                        base_overlap = base_overlap.intersection(mrf_rows.index)
                    if len(base_overlap) == 0:
                        # Fall back to whatever observed+inflow support is available for the
                        # reservoir so FE Walter/Prompton still get lower-basin context figures.
                        base_overlap = pd.Index(inflow_df.index)
                        base_overlap = base_overlap.intersection(obs_storage.dropna().index)
                        if obs_release is not None:
                            base_overlap = base_overlap.intersection(obs_release.dropna().index)
                    base_overlap = base_overlap[
                        (base_overlap >= pd.Timestamp(PLOT_START))
                        & (base_overlap <= pd.Timestamp(PLOT_END))
                    ]
                    seen_five_windows: set[tuple[str, str]] = set()
                    for win_name, wstart, wend in windows:
                        five_start, five_end = wstart, wend
                        if args.mrf_overlap_only:
                            overlap = base_overlap[
                                (base_overlap >= pd.Timestamp(wstart))
                                & (base_overlap <= pd.Timestamp(wend))
                            ]
                            if len(overlap) > 0:
                                five_start = str(overlap.min().date())
                                five_end = str(overlap.max().date())
                            elif len(base_overlap) > 0:
                                # Some reservoirs (e.g., FE Walter/Prompton) have no overlap in legacy
                                # 2010–2014 windows; fall back to their available overlap window.
                                five_start = str(base_overlap.min().date())
                                five_end = str(base_overlap.max().date())
                                win_name = f"{win_name}_fallback_available"
                        if (five_start, five_end) in seen_five_windows:
                            continue
                        seen_five_windows.add((five_start, five_end))
                        five_slicer = slice(five_start, five_end)
                        five_date_tag = figure_date_tag(five_start, five_end)
                        inflow_plot = inflow_df.loc[five_slicer][res].astype(float)
                        plot_lower_basin_fivepanel(
                            reservoir=res,
                            obs_inflow=inflow_plot,
                            obs_storage_mg=obs_storage,
                            obs_release=obs_release,
                            sim_storage_mg=pywr_Sv,
                            sim_release=pywr_Rv,
                            default_storage_mg=def_Sv,
                            default_release=def_Rv,
                            mrf_df=pywr_MRFv,
                            default_mrf_df=def_MRFv,
                            trenton_obs=obs_Tv,
                            trenton_sim=pywr_Tv,
                            trenton_default=def_Tv,
                            start=five_start,
                            end=five_end,
                            policy=pol,
                            pick_label=str(pick),
                            param_text="",
                            mrf_style=args.mrf_fivepanel_style,
                            rolling_days=args.mrf_rolling_days,
                            mrf_line_width=args.mrf_line_width,
                            trenton_line_width=args.mrf_line_width,
                            save_path=os.path.join(
                                outdir_five,
                                f"lower_basin_mrf_{res}_{pol}_{pick_filename_slug(pick)}_{five_date_tag}_{win_name}_with_pywr_default.png",
                            ) if (
                                def_Sv is not None
                                or def_Rv is not None
                                or def_Tv is not None
                                or def_MRFv is not None
                            ) else os.path.join(
                                outdir_five,
                                f"lower_basin_mrf_{res}_{pol}_{pick_filename_slug(pick)}_{five_date_tag}_{win_name}.png",
                            ),
                        )

                # Figure 8: residual diagnostics (release)
                sim_release_dict = {"Independent": indie_R, param_series_label: pywr_Rv}
                if def_Rv is not None:
                    sim_release_dict["Pywr Default"] = def_Rv

                if _v(8) and not args.skip_error_ts_release_multi and obs_release is not None:
                    fig8_start, fig8_end = _effective_plot_window(
                        [obs_release, indie_R, pywr_Rv, def_Rv],
                        PLOT_START,
                        PLOT_END,
                    )
                    fig8_tag = figure_date_tag(fig8_start, fig8_end)
                    fig8_combined = os.path.join(
                        outdir_fig6,
                        f"release_combined_{res}_{pol}_{pick_filename_slug(pick)}_{fig8_tag}.png",
                    )
                    plot_fig6_combined_release_diagnostics(
                        obs=obs_release,
                        sim_dict=sim_release_dict,
                        title_prefix=f"{res} {pol} {pick} ({fig8_start}–{fig8_end})",
                        save_path=fig8_combined,
                        start=fig8_start,
                        end=fig8_end,
                        window_days=60,
                        lowess_frac=0.10,
                        acceptable_band=None,
                        max_date_ticks=10,
                        downsample_step=2,
                        use_relative_error_pct=os.environ.get(
                            "CEE_RELEASE_ERROR_DIAG_RELATIVE_PCT", "1"
                        ).strip().lower()
                        not in ("0", "false", "no", "off"),
                    )
                    print(f"[✓] saved Figure 8 (combined diagnostics): {fig8_combined}")

                # Figure 11: Trenton flow diagnostics (timeseries + FDC)
                if _v(11):
                    sim_trenton = {param_series_label: pywr_Tv}
                    if def_Tv is not None:
                        sim_trenton["Pywr Default"] = def_Tv
                    fig11_start, fig11_end = _effective_plot_window(
                        [obs_Tv, pywr_Tv, def_Tv],
                        PLOT_START,
                        PLOT_END,
                    )
                    plot_trenton_timeseries_and_fdc(
                        obs=obs_Tv,
                        sim_dict=sim_trenton,
                        title_prefix=f"{res} {pol} {pick} ({fig11_start}–{fig11_end})",
                        save_path=os.path.join(
                            trenton_folder,
                            f"trenton_ts_fdc_{res}_{pol}_{pick_filename_slug(pick)}_{figure_date_tag(fig11_start, fig11_end)}.png",
                        ),
                        min_flow_target=trenton_target_v,
                    )

                # optional saves & comparisons
                tag = f"{res}_{pol}_{pick_filename_slug(pick)}"
                if args.save_series:
                    indie_R.to_csv(os.path.join(outdir, f"{tag}_indie_release.csv"), header=True)
                    indie_S.to_csv(os.path.join(outdir, f"{tag}_indie_storage.csv"), header=True)
                    pywr_Rv.to_csv(os.path.join(outdir, f"{tag}_pywr_release.csv"), header=True)
                    pywr_Sv.to_csv(os.path.join(outdir, f"{tag}_pywr_storage.csv"), header=True)

                if args.compare_series:
                    compare_series(indie_R, pywr_Rv, f"{res}:{pol}:{pick} release (indie vs pywr)",
                                   rtol=args.rtol, atol=args.atol)
                    compare_series(indie_S, pywr_Sv, f"{res}:{pol}:{pick} storage (indie vs pywr)",
                                   rtol=args.rtol, atol=args.atol)

    print("DONE.")


if __name__ == "__main__":
    main()